import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync, copyFileSync } from 'node:fs';
import { join } from 'node:path';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { crc32 } from 'node:zlib';

const manifestPath = 'tools/marketing/assets.json';
const roots = ['packages/core/src', 'packages/shared/src', 'packages/receipt/src', 'packages/receipt/assets', 'packages/cli/src', 'apps/web/src', 'tools/marketing'];
function files(path) {
  return readdirSync(path, { withFileTypes: true }).flatMap(entry => entry.isDirectory() ? files(join(path, entry.name)) : [join(path, entry.name)]);
}
const hash = path => createHash('sha256').update(readFileSync(path)).digest('hex');
export function inputs() {
  return Object.fromEntries([...roots.flatMap(files).filter(path => !/\.(test|spec)\.|assets\.json$|freshness\.mjs$|pages\.mjs$|inspect\.mjs$|README\.md$/.test(path)),
    'pnpm-lock.yaml', 'apps/web/project.json', 'apps/web/scripts/gen-og.ts', 'apps/web/scripts/lib/render.ts', 'apps/web/vite.config.ts', 'apps/web/svelte.config.js', 'tools/assemble-package.mjs', 'tools/copy-web-assets.mjs']
    .sort().map(path => [path, hash(path)]));
}
const outputs = ['receipt.png', 'wrapped.png', 'wrapped-yearly.png', 'dashboard.png', 'dashboard-corner.png', 'dashboard-narrow.png', 'terminal.mp4', 'terminal.png', 'og.png'];
export function checkManifest(manifest) {
  assert.deepEqual(inputs(), manifest.inputs, 'Marketing capture inputs changed. Run pnpm site:refresh.');
  for (const name of outputs) assert.equal(hash(`apps/site/public/shots/${name}`), manifest.outputs[name], `${name} is missing or changed. Run pnpm site:refresh.`);
}
function provenance(path) {
  const png = readFileSync(path);
  const chunks = [png.subarray(0, 8)];
  const origin = Buffer.from('impeccable:prompt\0Origin: actual production Chaching renderer, fictional tools/marketing/fixture.ts data, fixed 2026-08-31T18:00:00Z. See tools/marketing/assets.json for source and toolchain hashes.');
  const chunk = Buffer.alloc(origin.length + 12);
  chunk.writeUInt32BE(origin.length);
  chunk.write('tEXt', 4);
  origin.copy(chunk, 8);
  chunk.writeUInt32BE(crc32(chunk.subarray(4, -4)), chunk.length - 4);
  for (let offset = 8; offset < png.length;) {
    const length = png.readUInt32BE(offset) + 12;
    const type = png.toString('ascii', offset + 4, offset + 8);
    if (type === 'IEND') chunks.push(chunk);
    if (!(type === 'tEXt' && png.toString('utf8', offset + 8, offset + length - 4).startsWith('impeccable:prompt\0'))) chunks.push(png.subarray(offset, offset + length));
    offset += length;
  }
  writeFileSync(path, Buffer.concat(chunks));
}
if (process.argv.includes('--write')) {
  copyFileSync('apps/web/static/og.png', 'apps/site/public/shots/og.png');
  for (const name of outputs.filter(name => name.endsWith('.png'))) provenance(`apps/site/public/shots/${name}`);
  writeFileSync(manifestPath, JSON.stringify({ source: 'Fictional usage generated by tools/marketing/fixture.ts; rendered by production chaching code.',
    captureDate: '2026-08-31T18:00:00Z', node: process.version, platform: `${process.platform}-${process.arch}`,
    toolchain: Object.fromEntries([['vhs', ['--version']], ['ffmpeg', ['-version']], ['/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', ['--version']], ['docker', ['image', 'inspect', 'postgres:17', '--format', '{{index .RepoDigests 0}}']]].map(([command, args]) => [command, execFileSync(command, args, {encoding: 'utf8'}).trim().split('\n')[0]])),
    terminalFontSha256: hash(`${process.env.HOME}/Library/Fonts/JetBrainsMonoNerdFontMono-Regular.ttf`), inputs: inputs(),
    outputs: Object.fromEntries(outputs.map(name => [name, hash(`apps/site/public/shots/${name}`)])) }, null, 2) + '\n');
} else if (process.argv[1]?.endsWith('freshness.mjs')) {
  checkManifest(JSON.parse(readFileSync(manifestPath, 'utf8')));
  console.log('Marketing assets match their production sources and fixture.');
}
