import { execFileSync } from 'node:child_process';
import { createHash, randomUUID } from 'node:crypto';
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { Pool } from 'pg';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

const baseUrl = process.env.CHACHING_TEST_DATABASE_URL;
const enabled = baseUrl && process.env.CHACHING_TEST_PG_TOOLS === '1';
const suite = enabled ? describe : describe.skip;
suite('Packaged pool rollout rehearsal', () => {
 let directory: string;
 const database = 'chaching_rollout_' + randomUUID().replaceAll('-', '');
 const role = database + '_role';
 let admin: Pool;
 let db: Pool;
 let url: string;
 const script = resolve('docs/pool-rollout.mjs');
 const hash = (path: string) => createHash('sha256').update(readFileSync(path)).digest('hex');
 const run = (...args: string[]) => execFileSync(process.execPath, [script, ...args], {
  env: { ...process.env, CHACHING_DATABASE_URL: url }, encoding: 'utf8', stdio: ['pipe','pipe','pipe']
 });
 beforeAll(async () => {
  directory = mkdtempSync(join(tmpdir(), 'chaching-rollout-'));
  admin = new Pool({ connectionString: baseUrl });
  await admin.query(`CREATE DATABASE ${database}`);
  await admin.query(`CREATE ROLE ${role}`);
  const target = new URL(baseUrl!); target.pathname = '/' + database; url = target.href;
  db = new Pool({ connectionString: url });
  await db.query(readFileSync('src/lib/core/sync/fixtures/pool-v3.sql', 'utf8'));
  await db.query(`GRANT USAGE ON SCHEMA chaching_sync TO ${role}`);
  await db.query(`INSERT INTO chaching_sync.pool(id,name) VALUES('pool','Rehearsal');
   INSERT INTO chaching_sync.machine(pool_id,id,name,hostname) VALUES('pool','one','One','fixture');
   INSERT INTO chaching_sync.subscription(pool_id,id,provider,name,tier,monthly_usd) VALUES('pool','paid','claude','Paid','custom',123);
   INSERT INTO chaching_sync.machine_subscription VALUES('pool','one','claude','paid');
   INSERT INTO chaching_sync.machine_day_agg VALUES('pool','machine:one','one','2026-09-01','claude','model',100,20,0,0,0,0,0,0,1,12.5,0,false,now());`);
 }, 30000);
 afterAll(async () => {
  await db?.end(); await admin?.query(`DROP DATABASE IF EXISTS ${database}`); await admin?.query(`DROP ROLE IF EXISTS ${role}`); await admin?.end();
  if (directory) rmSync(directory, { recursive: true, force: true });
 });
 it('backs up, rejects drift, migrates twice, verifies and restores schema/config', async () => {
  const packageName = execFileSync('npm', ['pack','--ignore-scripts','--silent','--pack-destination',directory], { encoding:'utf8' }).trim();
  const artifact = join(directory, packageName);
  const config = join(directory, 'config.json');
  const oldConfig = JSON.stringify({ history: { enabled: true }, sync: { poolId:'pool',machineId:'one' } });
  writeFileSync(config, oldConfig);
  const history = join(directory,'history.db');
  const originalDb = new DatabaseSync(history);
  originalDb.exec('PRAGMA journal_mode=WAL; CREATE TABLE usage(cost REAL); INSERT INTO usage VALUES(12.5)');
  originalDb.close();
  const client = join(directory,'client');
  expect(run('backup-client',client,config,history,artifact)).toContain('verified');
  const clientManifest = join(client,'client.json');
  const rosterFile = join(directory,'roster.json');
  writeFileSync(rosterFile, JSON.stringify([{ poolId:'pool',machineId:'one',stopped:true,targetSha256:hash(artifact),backupManifest:clientManifest,backupSha256:hash(clientManifest) }]));
  const rollout = join(directory,'rollout');
  const validRoster = readFileSync(rosterFile);
  writeFileSync(rosterFile, '[]');
  expect(() => run('preflight',rollout,rosterFile,artifact,resolve('bin/chaching.js'))).toThrow();
  writeFileSync(rosterFile, validRoster);
  expect(run('preflight',rollout,rosterFile,artifact,resolve('bin/chaching.js'))).toContain('verified');
  expect(run('backup',rollout)).toContain('verified');
  const dumpPath = join(rollout,'pool.dump');
  const dump = readFileSync(dumpPath);
  writeFileSync(dumpPath, 'corrupt');
  expect(() => run('migrate',rollout)).toThrow();
  writeFileSync(dumpPath, dump);
  await db.query("UPDATE chaching_sync.subscription SET monthly_usd=999");
  expect(() => run('migrate',rollout)).toThrow();
  expect((await db.query('SELECT version FROM chaching_sync.schema_version')).rows[0].version).toBe(3);
  await db.query("UPDATE chaching_sync.subscription SET monthly_usd=123");
  expect(run('migrate',rollout)).toContain('verified');
  expect(run('migrate',rollout)).toContain('verified');
  expect(run('verify',rollout)).toContain('verified');
  expect(() => run('restore',rollout)).toThrow();
  await db.query(`DROP OWNED BY ${role}`);
  await admin.query(`DROP ROLE ${role}`);
  expect(() => run('restore',rollout,'--clients-stopped')).toThrow();
  expect((await db.query('SELECT version FROM chaching_sync.schema_version')).rows[0].version).toBe(4);
  await admin.query(`CREATE ROLE ${role}`);
  expect(run('restore',rollout,'--clients-stopped')).toContain('verified');
  expect((await db.query('SELECT monthly_usd FROM chaching_sync.subscription')).rows[0].monthly_usd).toBe(123);
  writeFileSync(config, '{"version":1}');
  const changedDb = new DatabaseSync(history); changedDb.exec('UPDATE usage SET cost=999'); changedDb.close();
  expect(run('restore-client',client,'--clients-stopped')).toContain('verified');
  expect(readFileSync(config,'utf8')).toBe(oldConfig);
  const restoredDb = new DatabaseSync(history, { readOnly:true });
  expect(restoredDb.prepare('SELECT cost FROM usage').get()?.cost).toBe(12.5); restoredDb.close();
 }, 60000);
});
